# Generated by Django 2.0.3 on 2019-05-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_job_map',
            name='job',
        ),
        migrations.AddField(
            model_name='user_job_map',
            name='job_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
