# Generated by Django 2.0.3 on 2019-05-13 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190512_1404'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jobs',
        ),
    ]
