# Generated by Django 2.0.3 on 2019-05-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20190520_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='img_url',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
