# Generated by Django 2.0.3 on 2019-05-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20190520_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='img_url',
            field=models.CharField(default="{% static 'zf-connect/images/avatar.svg' %}", max_length=150),
        ),
    ]
