# Generated by Django 2.0.3 on 2019-05-20 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20190520_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_detail',
            old_name='Job_title',
            new_name='job_title',
        ),
    ]
