# Generated by Django 2.2.1 on 2019-06-02 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20190520_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_detail',
            name='company',
        ),
        migrations.RemoveField(
            model_name='user_detail',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user_job_map',
            name='user',
        ),
        migrations.DeleteModel(
            name='company',
        ),
        migrations.DeleteModel(
            name='user_detail',
        ),
        migrations.DeleteModel(
            name='user_job_map',
        ),
    ]
